### PR TITLE
roman_to_decimal conversion function

### LINKED ISSUE #1: Create a function to convert roman numbers to decimal one

### PR DESCRIPTION
**Pull request by annebarb**
closes #1

### CODE REVIEW

**Review by bsurd — CHANGES_REQUESTED** [review]
Needs work:
- If the user would use lowercase letters by accident the conversion would fail
- With input IIIV it should return an error, but it passes

**Comment by annebarb** [comment]
Please review the changes after roman numeral rules were added!

**Review by bsurd — CHANGES_REQUESTED** [review]
Looks good overall... but:
- Input IXIV should be invalid, it is 13 but to write 13 you need to write XIII in roman characters. 

Enhancement idea maybe:
- You could convert all input to lower char values so it would not matter if the user used ```i``` or ```I```. He would always get a result regardless of the fact that he inputted ```iV``` or ```IV```.

**Review by bsurd — CHANGES_REQUESTED** [review]
```VIV``` should not be allowed as in order to write ```9``` you must use ```IX```

**Comment by annebarb** [comment]
- covered conversion function from roman to decimal and viceversa 
- all the valid/ invalid characters returned the expected result
- made some additional  notes for project tracking (should have been treated separately)

**Review by bsurd — APPROVED** [review]

**Pull request merged**
